server:
  port: 8081

spring:
  application:
    name: service-provider
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

  instance:
      lease-renewal-interval-in-seconds: 1
      lease-expiration-duration-in-seconds: 2
