
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8084
spring:
  application:
    name: service-feign555
  zipkin:
    base-url: http://localhost:9411   
feign:
    hystrix:
        enabled: true
